#!/usr/bin/env bash

export PATH="/opt/homebrew/opt/llvm@13/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/llvm@13/lib"
export CPPFLAGS="-I/opt/homebrew/opt/llvm@13/include"

TERM_PROGRAM=Apple_Terminal $(ghcup whereis stack) "$@"
