;;; init-fonts.el --- Settings for fonts.  -*- lexical-binding: t; -*-

;;; Commentary:

;;; Code:

;; Auto generated by cnfonts, modified by me.
;; <https://github.com/tumashu/cnfonts>
(when
    (display-graphic-p)
  (set-face-attribute
   'default nil
   :font
   (font-spec :name "-*-Monaco-medium-normal-normal-*-12-*-*-*-m-0-iso10646-1"
	      ;; using `describe-font' to get the name.
	      :weight 'normal
	      :slant 'normal
	      :size 14.5))
  (dolist
      (charset
       '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font
     (frame-parameter nil 'font)
     charset
     (font-spec :name "-*-Hiragino Sans GB-medium-normal-normal-*-*-*-*-*-p-0-iso10646-1"
		:weight 'normal
		:slant 'normal
		:size 15.0))))
(let
    ((emoji-supported-version "29.0"))
  (when
      (and
       (not
	(version< emacs-version emoji-supported-version))
       system-darwin-p)
    (set-fontset-font t 'emoji
		      '("Apple Color Emoji" . "iso10646-1")
		      nil 'prepend)
    )
  )
(provide 'init-fonts)
;;; Local Variables:
;;; coding: utf-8
;;; End:
;;; init-fonts.el ends here
