#+title: Dotfiles

* Intro

你最好添加 =--depth=1= 這樣的選項（在克隆的時候）。

我现在在使用 Nix 作为包管理器,用得很爽。我停止使用 Homebrew 了。

我的 =$HOME= 目录结构是：

#+begin_example
  /Users/wu/Projects
  └── Repositories
      ├── FreeBSD
      │   └── src
      ├── Kernel.org
      │   └── dash
      ├── Learning
      │   └── Emacs
      ├── My
      │   ├── Blog
      │   ├── Dotfiles
      │   └── Practice
      ├── NixOS
      │   └── nixpkgs
      └── OpenBSD

  14 directories, 0 files
#+end_example

Nix 的文档：[[https://nixos.org/manual/nix/stable/installation/upgrading.html][NixOS 手册]]。

#+begin_quote
  Multi-user Nix users on macOS can upgrade Nix by running the following command.
#+end_quote

#+begin_src shell
  sudo -i sh -c 'nix-channel --update && nix-env -iA nixpkgs.nix && launchctl remove org.nixos.nix-daemon && launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist'
#+end_src

** Requirement

#+begin_example
emacs 29
nix 2.25
...
#+end_example

* zsh

我正在使用来自 grml 的 =.zshrc= ，搭配修改自 grml 的 =.zshrc.local= 。
当然了，仓库中还有个叫做 =.zshrc= 的文件。可别误会，这是我自己配置的，
而不是 grml 的，现在我只是偶尔更新一下，当作一个备用选项。

这里我摘录一下 grml 的安装建议（说明）：

#+begin_src  shell
  wget -O .screenrc     https://git.grml.org/f/grml-etc-core/etc/grml/screenrc_generic
  wget -O .tmux.conf    https://git.grml.org/f/grml-etc-core/etc/tmux.conf
  wget -O .vimrc        https://git.grml.org/f/grml-etc-core/etc/vim/vimrc
  wget -O .zshrc        https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
#+end_src

Grml's [[https://grml.org/console][Offical Website]].

* .emacs.d

Using =use-package= and =evil= .

** 关于主题

使用 modus-themes。

** 关于字体

使用 =cnfonts= 这个包。

*** Requirements

#+BEGIN_EXAMPLE
Fonts:
  Iosevka
  Mononoki
  Fira Code
  all-then-icons-font
Library:
  Librime
#+END_EXAMPLE

** 关于第三方的包

我使用 git submodule 的方式管理第三方的包（也就是 non-elpa 的包）。
类似于这样的形式：

#+begin_src shell
  git submodule add git@github.com:tumashu/pyim.git
#+end_src

至于去更新这些 /site-lisp/ 需要这样：

#+begin_src shell
  git submodule update --init --recursive --remote
#+end_src

如果修改了 =.gitmodules= 文件，指定了 =submodule= 的 commit，那么你需要：

#+begin_src shell
  git submodule sync
  git submodule update --init
#+end_src

如果没有在克隆仓库的时候添加 =--reverse= 的选项，那么你需要：

#+begin_src shell
  git submodule init
#+end_src

关于这个，我最近也参考了一下 [[https://liujiacai.net/blog/2021/05/05/emacs-package/#headline-6][Keep coding, liujiacai's blog]]。

** haskell

善用 =haskell-process-load-or-reload= 。

* vim

抄袭 grml。

* Kde/Plasma

我以前是一个死忠的 gnome 用户。

但是现在，我已经无法再忍受 gnome 的一次次崩溃和错误，

所以, 我开始使用 KDE/Plasma 了。我使用的 Linux 发行版是 Gentoo Linux ，因为这个发行版的软件选择非常多。

至于内核就是主线内核，要么是加上了 ZFS 模块，要么是加上了 Xanmod 的 patch, 或者直接使用 gentoo-kernel-bin 这个二进制的内核。

* Terminal

Alacritty or Terminal.app
