#+title: Dotfiles

* Intro

你最好添加 =--depth=1= 這樣的選項（在克隆的時候）。

我现在在使用 Nix 作为包管理器,用得很爽。我停止使用 Homebrew 了。

我的 =$HOME= 目录结构是：

#+begin_example
  /Users/wu/Projects
  └── Repositories
      ├── FreeBSD
      │   └── src
      ├── Kernel.org
      │   └── dash
      ├── Learning
      │   └── Emacs
      ├── My
      │   ├── Blog
      │   ├── Dotfiles
      │   └── Practice
      ├── NixOS
      │   └── nixpkgs
      └── OpenBSD

  14 directories, 0 files
#+end_example

Nix 的文档：[[https://nixos.org/manual/nix/stable/installation/upgrading.html][NixOS 手册]]。

#+begin_quote
  Multi-user Nix users on macOS can upgrade Nix by running the following command.
#+end_quote

#+begin_src shell
  sudo -i sh -c 'nix-channel --update && nix-env -iA nixpkgs.nix && launchctl remove org.nixos.nix-daemon && launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist'
#+end_src

* zsh

我正在使用来自 grml 的 =.zshrc= ，搭配修改自 grml 的 =.zshrc.local= 。
当然了，仓库中还有个叫做 =.zshrc= 的文件。可别误会，这是我自己配置的，
而不是 grml 的，现在我只是偶尔更新一下，当作一个备用选项。

这里我摘录一下 grml 的安装建议（说明）：

#+begin_src  shell
  wget -O .screenrc     https://git.grml.org/f/grml-etc-core/etc/grml/screenrc_generic
  wget -O .tmux.conf    https://git.grml.org/f/grml-etc-core/etc/tmux.conf
  wget -O .vimrc        https://git.grml.org/f/grml-etc-core/etc/vim/vimrc
  wget -O .zshrc        https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
#+end_src

Grml's [[https://grml.org/console][Offical Website]].

* .emacs.d

我的 emacs 配置带有 vim 编辑器的按键绑定，使用了 evil 的方案。
我没有使用社区中比较流行的 use-package 或者 leaf.el ，而是选择了和 purcell 一样的方案 （实际上就是抄）。

Purcell 使用了一个叫作 =maybe-require-package= 的函数。我为这个函数写了一个包装的宏 =mrp= :

#+begin_src elisp
  (defmacro mrp (package-name &rest body)
    "It is a wrapper for `maybe-require-package'.
  And this macro only support a name of package."
    `(when (maybe-require-package (quote ,package-name))
       ,@body))

  (mrp hello)

  (macroexpand (quote (mrp hello (setq hello-setting t))))
#+end_src

这个宏并没有用在实际的配置中，因为我感觉也没什么太大的必要。而且功能也比较简陋，
比如说 =maybe-require-package= 这个函数的签名如下：

#+begin_src elisp
  (maybe-require-package PACKAGE &optional MIN-VERSION NO-REFRESH)
#+end_src

也就是说，这个函数还有两个参数。这两个参数在我的配置文件里虽然没有用到，但是还是有必要提一下。
我这个 =mrp= 宏更本没有考虑到这个问题。这个宏只是参考了常规配置模式，即:

#+begin_src elisp
  (when (maybe-require-package 'package-name)
    (setq package-settings t)
    ...)
#+end_src

这样的形式。

** 关于主题

使用 modus-themes。

** 关于字体

在 macOS(即 Darwin) 上，我使用 Monoca 字体和 SF Mono 字体。

至于中文字体，用了 tumashu 的 cnfonts 来完成设置。

顺便提一下，我就是在 emacs 上用 pyim 写这份文件的，感谢 tumashu 同学的努力 :)

** 关于第三方的插件

我使用 git submodule 的方式管理第三方的包（也就是 non-elpa 的包）。
类似于这样的形式：

#+begin_src shell
  git submodule add git@github.com:tumashu/pyim.git
#+end_src

至于去更新这些 /site-lisp/ 需要这样：

#+begin_src shell
  git submodule update
#+end_src

如果没有在克隆仓库的时候添加 =--reverse= 的选项，那么你需要：

#+begin_src shell
  git submodule init
#+end_src

** Tips

善用 =pp-buffer= 以及 =imenu=, 相比 =consult-ripgrep=, =rg.el= 或许更加适合我。

* vim

抄袭 grml。

* Kde/Plasma

我以前是一个死忠的 gnome 用户。

但是现在，我已经无法再忍受 gnome 的一次次崩溃和错误，

所以, 我开始使用 KDE/Plasma 了。我使用的 Linux 发行版是 Gentoo Linux ，因为这个发行版的软件选择非常多。

至于内核就是主线内核，要么是加上了 ZFS 模块，要么是加上了 Xanmod 的 patch, 或者直接使用 gentoo-kernel-bin 这个二进制的内核。
