# Filename: ~/.zprofile
# Author Thomas Wu <ixnij.wu@outlook.com>

# For homebrew:
# Prepare for homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Homebrew: Source
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.ustc.edu.cn/homebrew-core.git"
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.ustc.edu.cn/brew.git"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles"

# Homebrew: zsh completions
export FPATH=$(brew --prefix)/share/zsh/site-functions:~/.zfunc:$FPATH

# Homebrew: disable auto update.
export HOMEBREW_NO_AUTO_UPDATE=1

# For starship configuretion file path.
# export STARSHIP_CONFIG=~/.config/starship/config.toml

# For comman `fzf`
export FZF_DEFAULT_OPTS="--height 80% --layout=reverse --border --preview 'bat --style=numbers --color=always --theme=gruvbox-dark --line-range :500 {}'"
export FZF_COMPLETION_OPTS="--border --info=inline"
export FZF_DEFAUlT_COMMAND="fd --type f"

# On macOS:
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"

# For nix
export NIX_PATH=darwin-config=$HOME/.nixpkgs/darwin-configuration.nix:$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH

# End of file ##############################
# vim:filetype=zsh
# Local variables:
# mode: sh
# End:
# #########################################
