# For homebrew 
eval "$(/opt/homebrew/bin/brew shellenv)"
# Homebrew: Source
export HOMEBREW_CORE_GIT_REMOTE="https://git.sjtu.edu.cn/sjtug/homebrew-core.git"
export HOMEBREW_BREW_GIT_REMOTE="https://git.sjtu.edu.cn/sjtug/brew.git"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.sjtug.sjtu.edu.cn/homebrew-bottles/bottles"
# Homebrew: zsh completions
export FPATH=$(brew --prefix)/share/zsh/site-functions:~/.zfunc:$FPATH
