# Filename: ~/.zshrc
# Author: Thomas Wu <ixnij.wu@outlook.com>
# Local Variables:
# mode: sh
# End:

# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' menu select
zstyle ':completion:*' rehash true
zstyle ':completion:*' max-errors 5 not-numeric
zstyle ':completion::complete:*' gain-privileges 1
zstyle ':completion:*' use-cache on

# Global alias from ZSH-LOVERS(1)
alias -g CA="2>&1 | cat -A"
alias -g C='| wc -l'

alias e='emacsclient -t'
alias cat=bat

# Colors on GNU ls(1)
if ls --color=auto / >/dev/null 2>&1; then
    alias ls="ls --color=auto"
    # Colors on FreeBSD and OSX ls(1)
elif ls -G / >/dev/null 2>&1; then
    alias ls="ls -G"
fi

emulate -L zsh
autoload -Uz compinit
compinit

HISTFILE=~/.zsh_history
HISTSIZE=10000000
SAVEHIST=10000000

bindkey -e
# End of lines configured by zsh-newuser-install

local progs=(zoxide starship)

for prog ($progs) {
    eval "$($prog init zsh)"
}

[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh

fpath+=~/.zfunc
